repositories:
  - name: vaultwarden
    url: https://guerzon.github.io/vaultwarden
  - name: open-webui
    url: https://helm.openwebui.com
  - name: rphllc-glance
    url: https://rphllc.github.io/helm/glance

helmDefaults:
  wait: true
  timeout: 900

releases:
  - name: vaultwarden
    namespace: vaultwarden
    chart: vaultwarden/vaultwarden
    version: 0.31.8
    createNamespace: true
    atomic: true
    values:
      - values/common/storage-longhorn.yaml
      - values/vaultwarden/base.yaml

  - name: open-webui
    namespace: open-webui
    chart: open-webui/open-webui
    version: 7.2.0
    createNamespace: true
    atomic: true
    values:
      - values/common/storage-longhorn.yaml
      - values/open-webui/base.yaml

  - name: glance
    namespace: glance
    chart: rphllc-glance/glance
    version: 0.1.6
    createNamespace: true
    atomic: true
    values:
      - values/glance/base.yaml

  - name: glance-ingress
    namespace: glance
    chart: ./charts/ingress
    needs:
      - glance # ensure Service exists first
    values:
      - values/glance/ingress.yaml
